// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMAffinitySpec) DeepCopyInto(out *VMAffinitySpec) {
	*out = *in
	out.VMAntiAffinity = in.VMAntiAffinity
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMAffinitySpec.
func (in *VMAffinitySpec) DeepCopy() *VMAffinitySpec {
	if in == nil {
		return nil
	}
	out := new(VMAffinitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMAntiAffinitySpec) DeepCopyInto(out *VMAntiAffinitySpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMAntiAffinitySpec.
func (in *VMAntiAffinitySpec) DeepCopy() *VMAntiAffinitySpec {
	if in == nil {
		return nil
	}
	out := new(VMAntiAffinitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMNetworkSpec) DeepCopyInto(out *VMNetworkSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMNetworkSpec.
func (in *VMNetworkSpec) DeepCopy() *VMNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(VMNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSphereCompute) DeepCopyInto(out *VSphereCompute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSphereCompute.
func (in *VSphereCompute) DeepCopy() *VSphereCompute {
	if in == nil {
		return nil
	}
	out := new(VSphereCompute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VSphereCompute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSphereComputeList) DeepCopyInto(out *VSphereComputeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VSphereCompute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSphereComputeList.
func (in *VSphereComputeList) DeepCopy() *VSphereComputeList {
	if in == nil {
		return nil
	}
	out := new(VSphereComputeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VSphereComputeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSphereComputeSpec) DeepCopyInto(out *VSphereComputeSpec) {
	*out = *in
	out.Affinity = in.Affinity
	out.Networks = in.Networks
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSphereComputeSpec.
func (in *VSphereComputeSpec) DeepCopy() *VSphereComputeSpec {
	if in == nil {
		return nil
	}
	out := new(VSphereComputeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSphereComputeStatus) DeepCopyInto(out *VSphereComputeStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSphereComputeStatus.
func (in *VSphereComputeStatus) DeepCopy() *VSphereComputeStatus {
	if in == nil {
		return nil
	}
	out := new(VSphereComputeStatus)
	in.DeepCopyInto(out)
	return out
}
