kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vspherecompute
subjects:
- kind: ServiceAccount
  name: vspherecompute
roleRef:
  kind: Role
  name: vspherecompute
  apiGroup: rbac.authorization.k8s.io
